#!/bin/bash
ZPOOLNAME='zfs'
while read mountpoint
do
     original=${mountpoint}
     new=${mountpoint/${ZPOOLNAME}/disk1}
     mkdir -p ${new}
     mount --bind $original $new
done < <(zfs list -o mountpoint -t filesystem | sed '1,2d')
